version: 2
registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.REGISTRY_USERNAME}}}
    password: ${{secrets.REGISTRY_PASSWORD}}

updates:
  - package-ecosystem: "docker"
    directory: "/mathewfleisch/tools"
    registries:
      - dockerhub
    schedule:
      interval: "monthly"