# Name:        auto-merge-dependabot-prs.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will automatically merge any pull request
#              that was opened by dependabot
name: Auto-Merge Dependabot PRs
on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on: linter
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DOCKER_DEV_ENV_RW }}
          fetch-depth: 0

      -
        name: Set this_branch environment variable
        run: echo "this_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      -
        name: Git tag to trigger build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Merge $this_branch -> main"
          git checkout main
          git pull origin main
          git merge $this_branch
          git push origin main
          echo "Download semver tool"
          git fetch --tags
          currentTag=$(git tag --list | sort -V | tail -1)
          wget https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver -O ./semver
          chmod +x ./semver
          ./semver --version
          newTag=$(./semver bump patch $currentTag)
          echo "From: $currentTag -> To: $newTag"
          git tag "v${newTag}"
          git push origin "v${newTag}" --follow-tags
          echo "Dependabot PR auto-merge complete"
