name: auto-merge

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
