name: auto-merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
      -
        name: Git tag to trigger build
        run: |
          currentTag=$(git tag --list | sort -V | tail -1)
          newTag=$(semver bump patch $currentTag)
          git tag "v${newTag}"
          git push origin "v${newTag}"

