# Name:        auto-merge-dependabot-prs.yaml
# Author:      Mathew Fleisch <mathew.fleisch@gmail.com>
# Description: This action will automatically merge any pull request
#              that was opened by dependabot
name: Auto-Merge Dependabot PRs
on:
  pull_request_target:
    
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: Auto-Merge Dependabot PRs
    runs-on:
      - self-hosted
      - linter
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.0
        with:
          github-token: "${{ secrets.GIT_TOKEN }}"

      - name: Setup Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
 
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DOCKER_DEV_ENV_RW }}
          ref: main
          fetch-depth: 0

      -
        name: Install stuff with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            semver 3.3.0

      -
        name: Git tag to trigger build
        run: |
          echo "Download semver tool"
          git fetch --tags
          currentTag=$(git tag --list | sort -V | tail -1)
          semver --version
          newTag=$(semver bump patch $currentTag)
          echo "From: $currentTag -> To: $newTag"
          git tag "v${newTag}"
          git push origin "v${newTag}" --follow-tags
          echo "Dependabot PR auto-merge complete"
