name: auto-merge

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
      -
        name: Git tag to trigger build
        run: |
          git fetch --tags
          currentTag=$(git tag --list | sort -V | tail -1)
          wget https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver -O ./semver
          chmod +x ./semver
          ./semver --version
          echo "Current Tag: $currentTag"
          newTag=$(./semver bump patch $currentTag)
          echo "New Tag: $newTag"
          git tag "v${newTag}"
          git push origin "v${newTag}"

